# GitHub Sponsors
github: UsamaSarwar

# Other funding platforms
custom: 
  - https://buymeacoffee.com/usamasarwar
  - https://ko-fi.com/usamasarwar
  - https://paypal.me/usamasarwarpro

# Social media for support and engagement
# Twitter: @UsamaSarwarPro
# LinkedIn: linkedin.com/in/UsamaSarwarPro
# YouTube: youtube.com/UsamaSarwar
# Instagram: instagram.com/UsamaSarwarPro
